// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP9rGTu7EaiNuzyvuC7FFzA0hHte4Wpzk',
    appId: '1:346433396765:web:284a9ef71156c50013a6f4',
    messagingSenderId: '346433396765',
    projectId: 'learncraft-5145',
    authDomain: 'learncraft-5145.firebaseapp.com',
    storageBucket: 'learncraft-5145.firebasestorage.app',
    measurementId: 'G-J2LMDXMYJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTOJqUC-3thFyfWYGayAVfRAVqRr8a7ug',
    appId: '1:346433396765:android:716c695b8c7d4eca13a6f4',
    messagingSenderId: '346433396765',
    projectId: 'learncraft-5145',
    storageBucket: 'learncraft-5145.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm_aizlxFDQi5C910prT6ITt4CBb9Hp0s',
    appId: '1:346433396765:ios:1b7c2553cd57c10d13a6f4',
    messagingSenderId: '346433396765',
    projectId: 'learncraft-5145',
    storageBucket: 'learncraft-5145.firebasestorage.app',
    iosBundleId: 'com.example.learnCraftStu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm_aizlxFDQi5C910prT6ITt4CBb9Hp0s',
    appId: '1:346433396765:ios:1b7c2553cd57c10d13a6f4',
    messagingSenderId: '346433396765',
    projectId: 'learncraft-5145',
    storageBucket: 'learncraft-5145.firebasestorage.app',
    iosBundleId: 'com.example.learnCraftStu',
  );
}
